language: php

sudo: false

notifications:
    email: deploy@peter-gribanov.ru

os:
    - linux
    - osx

branches:
  except:
    - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
        - php: 5.4
        - php: 5.3
          dist: precise
        - php: 5.4
          env: RUNKIT=1
        - php: hhvm
          sudo: required
          dist: trusty
          group: edge
    allow_failures:
      - os: osx

before_install:
    - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then echo 'xdebug.enable = on' >> /etc/hhvm/php.ini; fi
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

before_script:
    - if [ "$RUNKIT" = "1" ]; then git clone --depth=1 git://github.com/zenovich/runkit.git; fi;
    - if [ "$RUNKIT" = "1" ]; then cd runkit && phpize && ./configure && make && make install && cd ../; fi;
    - if [ "$RUNKIT" = "1" ]; then phpenv config-add tests/travis.runkit.ini; fi;
    - composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - vendor/bin/phpunit --coverage-clover build/coverage-clover.xml

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
