language: php

sudo: false

notifications:
    email: deploy@peter-gribanov.ru

os:
    - linux
    - osx

branches:
  except:
    - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
        - php: 5.4
        - php: 5.3
          dist: precise
    allow_failures:
      - os: osx

before_install:
    - git clone --depth=1 git://github.com/zenovich/runkit.git
    - cd runkit
    - phpize
    - ./configure
    - make
    - make install
    - cd ../
    - phpenv config-add tests/travis.runkit.ini

before_script:
    - composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - vendor/bin/phpunit --coverage-clover build/coverage-clover.xml

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
