language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

os:
    - linux
    - osx

matrix:
    allow_failures:
      - os: osx

notifications:
    email: info@peter-gribanov.ru

install:
    - composer self-update
    - composer --version
    - composer install --prefer-dist

script:
    - phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
